### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LeonMazzoli** [AyzrixYTB/SimpleFaction#51] opened 2021-08-24 22:13 UTC
[15:02:18] [Server thread/CRITICAL]: ErrorException: "Undefined index: MonnaieCiel559" (EXCEPTION) in "plugins/SimpleFaction/src/Ayzrix/SimpleFaction/API/FactionsAPI" at line 645
[15:02:18] [Server thread/CRITICAL]: #0 plugins/SimpleFaction/src/Ayzrix/SimpleFaction/API/FactionsAPI(645): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[31] Undefined index: MonnaieCiel559, string[82] /home/container/plugins/SimpleFaction/src/Ayzrix/SimpleFaction/API/FactionsAPI.p, integer 645, array[2])
[15:02:18] [Server thread/CRITICAL]: #1 plugins/SimpleFaction/src/Ayzrix/SimpleFaction/Events/Listener/EntityListener(32): Ayzrix\SimpleFaction\API\FactionsAPI::areAllies(string[14] MonnaieCiel559, string[5] AfteR)
[15:02:18] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): Ayzrix\SimpleFaction\Events\Listener\EntityListener->EntityDamageByEntity(object pocketmine\event\entity\EntityDamageByEntityEvent)
[15:02:18] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Ayzrix\SimpleFaction\Events\Listener\EntityListener, object pocketmine\event\entity\EntityDamageByEntityEvent)
[15:02:18] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
[15:02:18] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/entity/Entity(932): pocketmine\event\Event->call()
[15:02:18] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/entity/Living(552): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
[15:02:18] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/Player(3941): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
[15:02:18] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/Player(2742): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
[15:02:18] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(149): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[15:02:18] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(106): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[15:02:18] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[15:02:18] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[15:02:18] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[15:02:18] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Player(3321): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[15:02:18] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[15:02:18] [Server thread/CRITICAL]: #16 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 86.202.138.221 49989, object raklib\protocol\EncapsulatedPacket, integer 0)
[15:02:18] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[15:02:18] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[15:02:18] [Server thread/CRITICAL]: #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[15:02:18] [Server thread/CRITICAL]: #20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
[15:02:18] [Server thread/CRITICAL]: #21 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1628866938.5505)
[15:02:18] [Server thread/CRITICAL]: #22 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
[15:02:18] [Server thread/CRITICAL]: #23 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
[15:02:18] [Server thread/CRITICAL]: #24 pmsrc/src/pocketmine/PocketMine(311): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[15:02:18] [Server thread/CRITICAL]: #25 pmsrc/src/pocketmine/PocketMine(341): pocketmine\server()
[15:02:18] [Server thread/CRITICAL]: #26 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[15:02:18] [Server thread/INFO]: Fir3RusH6297[/86.202.138.221:49989] logged out due to Internal server error

**Comment by AyzrixYTB** [comment] 2021-09-20 19:22
Duplicate of #46

**Closed as completed by AyzrixYTB** 2021-09-20 19:22 UTC
