### ISSUE TITLE
Undefined Index bug

### ISSUE THREAD

**Issue by JonyGamesYT9** [AyzrixYTB/SimpleFaction#50] opened 2021-08-21 05:58 UTC
ErrorException: "Undefined index: Raynul" (EXCEPTION) in "plugins/SimpleFaction.phar/src/Ayzrix/Simple
Faction/API/FactionsAPI" at line 653

**Comment by AyzrixYTB** [comment] 2021-09-20 19:22
Duplicate of #46

**Closed as completed by AyzrixYTB** 2021-09-20 19:22 UTC
